language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - 'node_modules'
install:
  - npm install coveralls
  - npm install
script:
  - npm run lint
  - npm test -- -u --coverage
after_success:
   - coveralls < coverage/lcov.info
